var mysql = require('./mysql/mysql');

/*
var dbhandle_m = 'game_master_m';
var dbhandle_s = 'game_master_s';
var mysql_m = mysql.init(dbhandle_m);
var mysql_s = mysql.init(dbhandle_s);
console.log('in loginDao');
console.log(mysql_m);
console.log(mysql_s);
*/
var loginDao = module.exports;

var gdb = require('util');

/**
 * Create a new user
 * @param {String} device_info  unique string generated by app/apk
 * @param {String} login_name  
 * @param {String} password_hash 
 * @param {Number} created_on registed datetime
 */
loginDao.createUser = function (dbhandle, deviceInfo, loginName, passwordHash, cb) {
  var insertSQL = 
    'insert into login_data(device_info, login_name, password_hash, created_on) values (?,?,?,?)';
  var createdOn   = Math.round(new Date().getTime()/1000); // unixtime
  var args = [deviceInfo, loginName, passwordHash, createdOn];
  console.log(deviceInfo + loginName + passwordHash + createdOn);
  dbhandle.insert(insertSQL, args, function(err, res) {
    if (err !== null) {
      console.log(err);
      cb({code: err.number, msg: err.message}, null);
    }
    else {
      var user = {id:res.insertId, name:loginName, lastLoginTime:createdOn};
      cb(null, user);
    }
  });
};

/**
 * Get loginData by deviceInfo
 * @param {String} dbhandle handle for Master DB or Slave DB, default is Slave DB
 * @param {String} deviceInfo  unique string generate by app/apk 
 * @param {function} cb
 * @returns {Object} loginData or null
 */
loginDao.getLoginDataByDeviceInfo = function (dbhandle, deviceInfo, cb) {
  var selectSQL = 'select * from login_data where device_info = ?'; 
  var args = [deviceInfo];
  console.log("------222-------");
  console.log(deviceInfo);
  console.log(dbhandle);

  dbhandle.query(selectSQL, args, function(err, res) {
    if (err !== null) {
      console.log("------444-------");
      cb(err.message, null);
    }
    else {
    console.log(gdb.inspect(res));
      if (!!res && res.length === 1) {
        console.log('in if');
        console.log(res);
        var rs = res[0];
        var user = {id:rs.uid, name:rs.login_name};
        cb(null, user);
      }
      else {
        console.log('in else');
        console.log(gdb.inspect(cb));
        console.log("------666-------");
        console.log(gdb.inspect(user));
        cb(null, null);
      }
    }
  });
};

/**
 * Get loginData by loginName
 * @param {String} dbhandle handle for Master DB or Slave DB, default is Slave DB
 * @param {String} loginName 
 * @param {function} cb
 * @returns {Object} loginData or null
 */
loginDao.getLoginDataByLoginName = function (dbhandle, loginName, cb) {
  var selectSQL = 'select * from login_data where login_name = ?'; 
  var args = [loginName];

  console.log("------555-------");
  console.log("dbhandle:");
  console.log(dbhandle);
  console.log("------556-------");

  dbhandle.query(selectSQL, args, function(err, res) {
    if (err !== null) {
      console.log(err);
      console.log(device_info);
      cb(err.message, null);
    }
    else {
      if (!!res && res.length === 1) {
        console.log('in if');
        console.log(res);
        var rs = res[0];
        var user = {id:rs.uid, name:rs.login_name, psw:rs.password_hash};
        cb(null, user);
      }
      else {
        console.log('in else');
        cb(null, null);
      }
    }
  });
};

/**
 * Update password_hash by userId
 * @param {String} passwordHash
 * @param {Number} userId
 */
loginDao.updatePassword = function (dbhandle, passwordHash, userId, cb) {
  var updateSQL = 'update login_data set password_hash=? where uid=?'; 
  var args = [passwordHash, userId];

  dbhandle.query(updateSQL, args, function(err, res) {
    if (err !== null) {
      console.log(err);
      cb(err.message, null);
    }
    else {
      if (!!res && res.affectedRows > 0) {
        console.log('in if');
        console.log(res);
        cb(null, true);
      }
      else {
        console.log('in else');
        cb(' failed ', null);
      }
    }
  });
};

