module.exports = {
  HP:     1,    // "生命"
  ATK:    2,    // "攻击"
  DEF:    3,    // "防御"
  AGI:    4,    // "敏捷"
  CRIT:   5,    // "暴击"
  IMPALE: 6,    // "穿刺"
  BLOCK:  7,    // "格挡"
  KILL:   8,    // "必杀"
  DODGE:  9,    // "闪避"
  HIT:    10,   // "命中"
  DOUBLE: 11,   // "连击"
  CTATK:  12,   // "反击"
  THUMP:  13,   // "重击"
  CONFRONT:14,  // "招架"
  LOYAL:  15,   // "忠诚"
  POWER:  16,   // "体力"
  ENERGY: 17,   // "斗志"
  WEAPON: 18,   // "武器"
  DEFENDER:19,  // "防具"
  SHOE:   20,   // "鞋子"
  JEWELRY:21,   // "饰品"
  KILL:   22,   // "必杀"
  THUNDER:23,   // "弱化防御"
  ICE:    24,   // "限制行动"
  FIRE:   25,   // "弱化攻击"
  WIND:   26,   // "持续伤害"
  WATER:  27,   // "恢复血量"
};
